git:
  pagers:
    - colorArg: always
      pager: delta --dark --features kanagawa-dragon --paging=never
  parseEmoji: true
gui:
  border: rounded
  mainPanelSplitMode: vertical
  showFileTree: true
  showRandomTip: false
  showBottomLine: true
  showPanelJumps: false
  nerdFontsVersion: "3"
  authorColors:
    "*": "#c5c9c5"
  branchColors:
    "main": "#c4746e"
    "master": "#c4746e"
    "develop": "#8a9a7b"
    "dev": "#8a9a7b"
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    rate: 80
  theme:
    activeBorderColor:
      - "#8a9a7b"
      - bold
    inactiveBorderColor:
      - "#a6a69c"
    optionsTextColor:
      - "#8ba4b0"
    selectedLineBgColor:
      - "#282727"
    cherryPickedCommitBgColor:
      - "#393836"
    cherryPickedCommitFgColor:
      - "#8a9a7b"
    unstagedChangesColor:
      - "#c4746e"
    defaultFgColor:
      - "#c5c9c5"
    searchingActiveBorderColor:
      - "#c4b28a"
